[project]
name = "rag-chatbot"
version = "0.1.0"
description = "RAG Chatbot for research papers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.125.0",
    "streamlit>=1.52.2",
]
